### ISSUE TITLE
Supported Algos

### ISSUE THREAD

**Issue by nyaaaaaaatalie** [duggerd/SoftwareAuthKeyLoader#2]
Hi, I see some references in here to AES128, I was wondering if that was the only algorithm supported. I want to be able to load DES-OFB keys into my radio. Is this possible currently, planned in the roadmap, or is it something I will need to implement?

**Comment by duggerd** [comment]
AES-128 is the only algorithm supported for P25 radio authentication, which this utility loads keys for. It does not load keys for P25 traffic encryption (such as AES-256 or DES-OFB or DES-XL or ADP) - the KFDtool project does that. However, it requires special hardware as it communicates with a different part of the radio to load traffic encryption keys rather than authentication keys like this utility does.

https://github.com/KFDtool/KFDtool
